---
name: Dwarf
slug: :dwarf
ability_scores:
  con: 2
age_range: !ruby/range
  begin: 50
  end: 350
  excl: false
recommended_alignments:
- :lawful
- :good
game_size: :medium
speed: 25
weapon_proficiencies:
- :battleaxe
- :handaxe
- :throwing_hammer
- :warhammer
tool_proficiencies_option:
  quantity: 1
  items:
  - :smith
  - :brewer
  - :mason
languages:
- :common
- :dwarvish
race_powers:
- name: Dwarven Resilience
  description: >
    You have advantage on saving throws against poison, and
    you have resistance against poison damage.
- name: Stonecunning
  description: >
    Whenever you make an Intelligence(History) check related
    to the origin of stonework, you are considered proficient in the
    History skill and add double your proficiency bonus to the check,
    instead of your normal proficiency bonus
race_variants:
- name: Hill Dwarf
  slug: :hill_dwarf
  ability_scores:
    wis: 1
  extra_hit_points_per_level: 1
- name: Mountain Dwarf
  slug: :mountain_dwarf
  ability_scores:
    str: 2
  armor_proficiencies:
  - :light
  - :medium
